package factor.labs.indiancalendar.utils.database;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "EVENTS".
 */
@Entity
public class Events {

    @Id(autoincrement = true)
    private Long id;
    private String GUID;
    private String name;
    private String property;
    private Long category;
    private Long sub_category;
    private String locations;
    private Long flags;
    private String tags;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated(hash = 2113269558)
    public Events() {
    }

    public Events(Long id) {
        this.id = id;
    }

    @Generated(hash = 756876280)
    public Events(Long id, String GUID, String name, String property, Long category, Long sub_category, String locations, Long flags, String tags) {
        this.id = id;
        this.GUID = GUID;
        this.name = name;
        this.property = property;
        this.category = category;
        this.sub_category = sub_category;
        this.locations = locations;
        this.flags = flags;
        this.tags = tags;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getGUID() {
        return GUID;
    }

    public void setGUID(String GUID) {
        this.GUID = GUID;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getProperty() {
        return property;
    }

    public void setProperty(String property) {
        this.property = property;
    }

    public Long getCategory() {
        return category;
    }

    public void setCategory(Long category) {
        this.category = category;
    }

    public Long getSub_category() {
        return sub_category;
    }

    public void setSub_category(Long sub_category) {
        this.sub_category = sub_category;
    }

    public String getLocations() {
        return locations;
    }

    public void setLocations(String locations) {
        this.locations = locations;
    }

    public Long getFlags() {
        return flags;
    }

    public void setFlags(Long flags) {
        this.flags = flags;
    }

    public String getTags() {
        return tags;
    }

    public void setTags(String tags) {
        this.tags = tags;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
